package src;

import java.util.ArrayList;
import java.util.List;

public class Solver {
    public static int boardsCreated = 0;

    public static ArrayList<Board> solveBoard(Board board, ArrayList<Move[]> moveHistory) {
        boardsCreated = 0;
        ArrayList<Board> solution = new ArrayList<>();
        solution.add(board);

        moveHistory.add(new Move[]{}); // Add an empty array since the first board isn't generated by a move

        while (true) {
            // Iterative Deepening Search (IDS) with a depth limit of 4

            Move[] forcedMoves = null;
            int depthLimitAt = 0;
            for (int depthLimit = 0; depthLimit <= 4; depthLimit++) {

                if (depthLimit >= 0) {
                    System.out.println("Searching for forced moves at depth " + depthLimit + " - Created " + boardsCreated + " boards so far");
                }

                // Try to find a forced move
                forcedMoves = findForcedMove(solution.get(solution.size() - 1), depthLimit);
                if (forcedMoves != null || board.isSolved()) {
                    depthLimitAt = depthLimit;
                    break;
                }
            }
            if (forcedMoves == null) {
                // No forced move found; return the current solution
                return solution;
            }

            try {
                Board newBoard = new Board(solution.get(solution.size() - 1));
                boardsCreated++;
                for (Move forcedMove : forcedMoves) {
                    newBoard.applyMove(forcedMove);
                }
                moveHistory.add(forcedMoves);
                solution.add(newBoard);
                if (depthLimitAt > 0) {
                    System.out.println("Found forced move: at d=" + depthLimitAt + " " + forcedMoves[0] + (forcedMoves.length > 1 ? " and " + forcedMoves[1] : "") + " - Created " + boardsCreated + " boards so far");
                    System.out.println(newBoard.simpleReadout());
                } else if (depthLimitAt == 0) {
                    System.out.println("Found forced move: at d=" + depthLimitAt + " " + forcedMoves[0] + (forcedMoves.length > 1 ? " and " + forcedMoves[1] : "") + " - Created " + boardsCreated + " boards so far");
                    System.out.println(newBoard.simpleReadout());
                }
                if (newBoard.isSolved()) {
                    System.out.println("Board is solved! - Created " + boardsCreated + " boards in total");
                    return solution;
                }
            } catch (InvalidMoveException e) {
                // This shouldn't happen, but if it does, just return the current solution
                System.err.println("Invalid move: " + e.getMessage());
                return solution;
            }
        }
    }

    // Returns an array because it's possible for one location to have multiple forced moves (e.g. a corner)
    public static Move[] findForcedMove(Board board, int depthLimit) {

        ArrayList<Location> openLocations = board.getOpenLocations();

        // Check locations with fewer connection possibilities and more open connections first
        // From lowest to highest on countMoveCombinations
        sortLocationsByConnections(openLocations, board);

        // Like the above, but operating on move combinations rather than individual moves
        for (Location loc : openLocations) {
            ArrayList<Move[]> combos = loc.getValidMoveCombinations(board);
            ArrayList<Move[]> validCombos = new ArrayList<>();
            for (Move[] combo : combos) {
                Board testBoard = new Board(board);
                boardsCreated++;
                try {
                    testBoard.applyMoves(combo);
                } catch (InvalidMoveException e) {
                    // Skip this move combo, don't check the resulting board
                    continue;
                }

                if (depthLimit > 0 && isDeadly(testBoard, depthLimit, combo[0].getStart())) {
                    // This move combination leads to a deadly board; skip it
                    continue;
                }

                validCombos.add(combo);

                if (validCombos.size() > 1) {
                    continue;      // If there's more than one valid combination, we already know there's no forced move here
                }
            }

            if (validCombos.size() == 0) {
                // If there are no valid combinations left, we shouldn't be here
                System.err.println("Location " + loc.getCoordinate() + " has no valid move combinations");
                return null;
            } else if (validCombos.size() == 1) {
                // If there's only one combination left, return it
                return validCombos.get(0);
            }

        }
        return null;
    }

    // A board is deadly if there are no valid moves from an open location, or if all valid moves from an open location lead to a deadly board
    public static boolean isDeadly(Board board, int depthLimit, Coordinate target) {
        if (depthLimit == 0) {
            // Too deep; give up
            return false;
        }

        // Get all open locations on the board and sort to put the most promising ones first
        ArrayList<Location> openLocations = board.getOpenLocations();
        if (target == null) {
            // Sort by the number of connections available to find a promising location, wherever it is
            sortLocationsByConnections(openLocations, board);
        } else {
            // Sort by the distance to the target to quickly evaluate a move at a particular location
            sortLocationsByDistance(openLocations, target);
        }

        // Check all open locations for forced moves
        for (Location loc : openLocations) {
            ArrayList<Move[]> moveCombos = loc.getValidMoveCombinations(board);
            if (moveCombos.isEmpty()) {
                return true; // No valid move combinations from this location, so this move is deadly
            }

            // Check to see if there is at least one valid, non-deadly move
            boolean hasValidCombo = false;
            for (Move[] combo : moveCombos) {
                Board newBoard = new Board(board);
                try {
                    newBoard.applyMoves(combo);
                } catch (InvalidMoveException e) {
                    // Invalid move; skip this one
                    continue;
                }
                if (depthLimit == 0 || !isDeadly(newBoard, depthLimit - 1, combo[0].getStart())) {      // Since all moves in the combo start from the same location, we can just pick the first one
                    hasValidCombo = true;
                    continue; // Don't bother checking the rest of the combos, all we need is one that's valid
                }
            }

            if (!hasValidCombo) {
                return true; // There's at least one location with no valid move combinations, which means this whole branch of the search tree is invalid
            }
        }
        return false; // All open locations have at least one valid move combination; the search tree can continue from here
    }

    // It's important for performance to pick good locations first - we choose the ones with the most restricted connections first
    // I make this a total ordering so the search is deterministic
    public static void sortLocationsByConnections(List<Location> locations, Board board) {
        locations.sort((a, b) -> {
            // Sort by the number of move combinations available at each location
            int aCount = a.countMoveCombinations(board);
            int bCount = b.countMoveCombinations(board);

            // If the counts are not equal, sort by that
            if (aCount != bCount) {
                return Integer.compare(aCount, bCount);
            }

            // If the counts are equal, sort by the xcoordinate, then by the ycoordinate
            if (a.getCoordinate().getRow() != b.getCoordinate().getRow()) {
                return Integer.compare(a.getCoordinate().getRow(), b.getCoordinate().getRow());
            } else {
                return Integer.compare(a.getCoordinate().getCol(), b.getCoordinate().getCol());
            }
        });
    }

    public static void sortLocationsByDistance(List<Location> locations, Coordinate target) {
        locations.sort((a, b) -> {
            // Sort by the distance to the target coordinate
            int aDistance = a.getCoordinate().manhattanDistance(target);
            int bDistance = b.getCoordinate().manhattanDistance(target);

            // If the distances are not equal, sort by that
            if (aDistance != bDistance) {
                return Integer.compare(aDistance, bDistance);
            }

            // If the distances are equal, sort by the xcoordinate, then by the ycoordinate
            if (a.getCoordinate().getRow() != b.getCoordinate().getRow()) {
                return Integer.compare(a.getCoordinate().getRow(), b.getCoordinate().getRow());
            } else {
                return Integer.compare(a.getCoordinate().getCol(), b.getCoordinate().getCol());
            }
        });
    }
}